### ISSUE TITLE
List of TODO issues after the 31-10-21 release

### ISSUE THREAD

**Issue by Ozymandias81** [Drugod/BloomProject#1]
RESOURCES
- [ ] add burning plus shock and swimming frames to RatDemons
- [ ] add crouch frames for Caleb and swimming frames for both classes
- [ ] add pickup sprites for GrenadeBox plus voxel and 3d model
- [ ] add swimming frames and underwater attack frames to Doom humans enemies
- [ ] add swimming frames and underwater attack frames to alternate cultists and chaingunner hybrids

CODING
- [x] it would be cool to hear screams when trains hit pedestrians or passes by (Rolls3d suggestion)
- [ ] add dropitem new ammo for flamethrower (fire cultimp) and the flamerthrower (mancubus/hybrids)
- [ ] choking hands should possess only humans already not possessed yet
- [ ] fix Doomguy skin palette
- [ ] fix GLDEFS for Doom enemies (RevenantTracer, Spidermastermind, others) and LifeLeech, check other stuff
- [ ] fix HUD statusbar for gzdoom 4+, or use GZDoom 3.7.2
- [ ] fix TERRAIN defs, lots of sounds needs to be defined and included
- [ ] polish overall code

:x:  reduce size of models skins, 1000x1000 is very engine intensive, 512x512 should be okay... We must figure how to not break quality though
- [x] remove unused stuff
- [ ] tweak special effects, bleeding effects and amount of used actors per maps
- [x] all bodies which fall over skies should fade immediately
- [x] bats, spiders and rats shouldn't be able to swim underwater
- [x] creatures which are able to jump shouldn't swim as well, beside RatDemons
- [x] jumping creatures and little ones such as spiders or rats should die immediately over skies (GargoDemon, RatDemons, SpiderMother too)
- [ ] some randomizers likes to spawn enemies in the void or in the sky, to be verified

**Comment by Drugod** [comment]
swming frames for rat demon? have no sense, in case should added swiming frames for cultist alternative also for chaingunners hybrids

**Comment by Ozymandias81** [comment]
Ratdemons can jump and for this reason they can also swim I think. Anyway you can edit my comment and add new tasks @Drugod :)
